### ISSUE TITLE
not playing nice with geom_raster/ geom_spatraster

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/gghdx#24]
just flagging an issue I found here so we can investigate further as time allows. I had originally thought it was an issue with the `{tidyterra}` package which is a nice convenience package for plotting spatraster objects in ggplot. However, when making a reprex to post I realized the issue disappears when `gghdx()` is not present. Therefore I've adapted that reprex for this repo:

``` r
library(terra)
#> terra 1.7.65
library(tidyterra)
#> 
#> Attaching package: 'tidyterra'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)
library(gghdx)

# recreate raster in question

# save dput output of value array
array_vals <- structure(c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                          NA, NA), dim = c(17L, 15L, 1L))

# set res
resx <- 0.08333333
resy <- 0.08333333

num_rows <-  17
num_cols <-  15
xmn <- 43.08333 - 0.5 * resx
xmx <-  44.33333 + 0.5 * resx
ymn <- 2.5- 0.5 * resy
ymx <- 3.916667+ 0.5 * resy

# generate SpatExtent
r_ext <-  terra::ext(xmn, xmx, ymn, ymx)

# generate spatRaster
r <- rast(
  x=array_vals,
  extent =r_ext,
  crs= "EPSG:4326"
)

# base plot -- looks good!
r |> plot()
```

![](https://i.imgur.com/Orickgt.png)

``` r


# ggplot (tidyterra) plot -- looks good
ggplot()+
  geom_spatraster(data=r)
```

![](https://i.imgur.com/OO1K1nK.png)

``` r
gghdx() # set gghdx

# ggplot (`{tidyterra}` + `{gghdx}`) plot -- looks wrong.
ggplot()+
  geom_spatraster(data=r)
```

![](https://i.imgur.com/L9xDPpM.png)

<sup>Created on 2024-04-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by zackarno** [comment]
After working through some more visuals - i  think i have a pretty strong lead on the issue:

If `gghdx()` is initiated this issue goes aways with following na.value arg shown below:
```
ggplot()+
  geom_spatraster(data=r) +
  scale_fill_continuous(na.value="transparent")
```

oddly `na.value=NA` or `na.value=NULL` don't work as expected. Therefore I'm guessing `gghdx()` is automatically setting the scale_fill_continuous without the `na.value="transparent"`

**Comment by caldwellst** [comment]
So, a few things, note that the same issue arises by default with using `{tidyterra}` scales:

```r
ggplot()+
  geom_spatraster(data=r) +
  scale_fill_whitebox_c()
```

I think it's because it's all trying to interpolate the fill value which is continuous. As you noted, we need `na.value = "transparent"`, and just adding that in the continuous scales for `gghdx()` produces the desired effect. That way, the default continuous scale and all default to transparent `NA` values, which I think is our desired behaviour anyway.

```r
ggplot()+
  geom_spatraster(data=r) +
  scale_fill_()
```

**Comment by zackarno** [comment]
interesting. Yes, thats a good call that `tidyterra::scale_fill_*()` create the same issue if `na.value="transparent"` is not specified. 

So yes, I think letting the user specify `na.value` makes sense. I also like the default behavior of ggplot2 of having na.value="transparent" when `scale_fill_*` is not specified. Therefore, it would be good if running `gghdx()` does not change this.

I see the linked PR and am playing with it now, so going to reply in there with a new issue that seems to be arising

**Comment by caldwellst** [comment]
Ha, and the new `{tidyterra}` has moved to using `"transparent"` as the default. Just noticed when testing this again. However, I think you should post this because it is still seemingly an error within the system, as I don't think this is normal behaviour.

**Comment by zackarno** [comment]
but it does seem like the correct behaviour? Could argue for another color rather than "transparent", but I don't think interpolating the non NA color band over NA values would make sense?
