### ISSUE TITLE
export for

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/gghdx#32]
Was utilizing this functionality in another project, and 3 small suggestions to make it more useful:

1. `export` the `format_number_hdx()` functionality 
2. change name to `number_hdx()`
3. more useful error message if user forgets a to include additional prefix... or maybe there should be no error?
 
I think numbers 1 & 2 would align it better to `{scales}` functions

https://github.com/OCHA-DAP/gghdx/blob/342afcf3fa67bd277c7dec62190db233b55321ff/R/label_number_hdx.R#L75

**Comment by caldwellst** [comment]
Yeah, I didn't originally export `format_...()` because all of those `format_...()` have been superseded in `{scales}`, but I think these are great ideas! And yeah, since users weren't intended to use `format_number_hdx()` hadn't added any checks to it, but will ensure it's user friendly.

**Comment by zackarno** [comment]
ah i didn't realize they were superseded, but seems useful to be able to run the formatting on any vector. I guess actually keeping the `format` in the function name either as prefix or suffix makes sense, so perhaps disregard my suggestion number 2

**Comment by caldwellst** [comment]
Yeah, I think I agree to add back `format_`, it's returning.
