### ISSUE TITLE
"gghdx.rdb is corrupt"

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/gghdx#34]
ran `devtools::install()` inside the `number-hdx` branch and got

```
Error: lazy-load database '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/gghdx/R/gghdx.rdb' is corrupt
In addition: Warning message:
internal error -3 in R_decompress1 
```

Then when run:

```
> library(gghdx)
Warning messages:
1: In get(name, envir = env) : internal error -3 in R_decompress1
2: In get(name, envir = env) : internal error -3 in R_decompress1
3: In get(name, envir = env) : internal error -3 in R_decompress1
4: In get(name, envir = env) : internal error -3 in R_decompress1
5: In get(name, envir = env) : internal error -3 in R_decompress1
```

By pressing `ctrl` + `shift` + `b` (`devtools::build()`) issue seems to resolve itself (no warnings and can load library)

Don't think the issue is specific to this package per se, as it seems like something I encountered before. I don't fully understand it, but figured i'd document  as it sort of relates to #26

**Comment by caldwellst** [comment]
Issue with R session that [requires restarting](https://stackoverflow.com/questions/10373098/error-in-fetchkey-internal-error-3-in-r-decompress1). `devtools::build()` automatically restarts the session, hence why it "fixed" the error.
