### ISSUE TITLE
Labels are really small

### ISSUE THREAD

**Issue by Rawa-Ganjani** [OCHA-DAP/gghdx#4]
the labels of the axises and values of the legend are hard to read on my machine,

![image](https://user-images.githubusercontent.com/16213008/184631938-8e8b8654-d2fe-42e2-acd1-9c7bc015d1df.png)

**Comment by Rawa-Ganjani** [comment]
after some trial and error, I realized that the problem occurs when using `gghdx()`, and if I use `theme_hdx' or `gghdx(showtext = FALSE)` everything would look normal, which indicates that the problem is with the fonts not being loaded and installing tidytext would basically solve this issue as well.

**Comment by caldwellst** [comment]
Will investigate with the other font issues.
